server:
  port: 8080
  servlet:
    context-path: /cosmeMgt

spring:
  application:
    name: cosmeMgt

  datasource:
    url: jdbc:postgresql://localhost:5432/cosme_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 36000 # in second
  refreshable-duration: 36000 # in seconds

momo:
  partner-code: MOMO
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_ACCESS_SECRET_KEY}
  redirect-url: http://localhost:3000/payment-result
  ipn-url: https://unsounded-unchurchly-kian.ngrok-free.dev/cosmeMgt/payments/ipn-url
  api-endpoint: https://test-payment.momo.vn/v2/gateway/api
  refund_url: /refund
  IS_PAYMENT_MOCKING: true      #mock payment for testing

vnpay:
  tmn-code: ${VNP_TMN_CODE}
  hash-secret: ${VPN_HASH_SECRET}
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:3000/payment-result" # URL FE sẽ hứng kết quả sau khi khách thanh toán xong
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction" # Dùng sau này nếu làm tính năng Hoàn tiền tự động
  version: "2.1.0"
  command: "pay"
  order-type: "other"

brevo:
  api.key: ${BREVO_API_KEY}
  sender:
    email: tranducphu.dtp@gmail.com
    name: Yesstyle
  brevo_url: https://api.brevo.com/v3/smtp/email

cloudinary:
  cloud_name: djhiau9nq
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET_KEY}