server:
  port: 8080
  servlet:
    context-path: /cosmeMgt

spring:
  application:
    name: cosmeMgt

  datasource:
    url: jdbc:postgresql://localhost:5432/cosme_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 36000 # in second
  refreshable-duration: 36000 # in seconds
  
momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  redirect-url: http://localhost:3000
  ipn-url: https://unsounded-unchurchly-kian.ngrok-free.dev/cosmeMgt/payments/ipn-url
  api-endpoint: https://test-payment.momo.vn/v2/gateway/api
  refund_url: /refund
  IS_PAYMENT_MOCKING: true      #mock payment for testing

brevo:
  api.key: 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
  sender:
    email: tranducphu.dtp@gmail.com
    name: Resto Restaurant
  brevo_url: https://api.brevo.com/v3/smtp/email

cloudinary:
  cloud_name: djhiau9nq
  api_key: 213478935551515
  api_secret: mLUq43xmb-kFsQarGlKUyMi3rVI
